
title: Crypt
email: your-email@example.com
description: Crypt
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:
github_username:
encoding: utf-8

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-coffeescript

sass:
    sass_dir: _assets

exclude:
  - vendor/

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

include:
    - _pages

assets:
  compress:
    css: true
    js: true
  cache: false

  autoprefixer:
    browsers:
      - "last 2 versions"
      - "IE > 9"

  skip_baseurl_with_cdn: false
  skip_prefix_with_cdn: false
  prefix: "/crypt/assets"
  assets:
    - "*.png"
    - "bundle.css"
  digest: true
  sources:
    - "_assets/folder"
    - "_assets/images/announcements"
    - "_assets/images/team"
    - "_includes/"
    - "_assets/js"
    - "_assets/css"
    - "_assets/css/components"
    - "_assets/fonts"
    - "_assets/images"
    - "_assets/images/announcements"
