# This is a basic workflow to help you get started with Actions
name: staging-build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    tags:
      - '*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    env:
      DIR_NAME: DIR_NAME
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set variables
        run: |
          export GIT_TAG=$(echo $GITHUB_REF | cut -d'/' -f 3 | sed -r 's/[.]+/-/g')
          export REPO_NAME=$(echo $GITHUB_REPOSITORY | cut -d'/' -f 2)
          export DIR_NAME="${REPO_NAME}--${GIT_TAG}"
          echo "DIR_NAME=$DIR_NAME" >> $GITHUB_ENV

      - name: Build docker image
        run: make build

      - name: Output dist
        run: make dist

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_WEBAPP }}
          aws-secret-access-key:  ${{ secrets.AWS_SECRET_ACCESS_KEY_WEBAPP }}
          aws-region: eu-west-1

      - name: Upload S3
        env:
          AWS_STAGING_BUCKET: ${{ secrets.AWS_STAGING_WEBAPP_BUCKET}}
        run: |
          echo "${AWS_BUCKET}/${DIR_NAME}"
          aws s3 sync _site/ $AWS_STAGING_BUCKET/$DIR_NAME  --cache-control="max-age=1576800000" --exclude "*.html" --exclude "raw/*"
          aws s3 sync _site/ $AWS_STAGING_BUCKET/$DIR_NAME  --cache-control="max-age=86400, no-cache" --exclude "*" --include "*.html"

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2.0.2
        env:
          SITE_NAME: ${{ env.DIR_NAME }}.dist.staging.hearxgroup.com
          HOST_NAME: Staging
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_CHANNEL_WEBSITE }}